Sources Sync custom metrics
RedHatInsights/topological_inventory-sync pull request #72
Opened 2020-10-12 06:52 UTC by slemrmartin

2020-10-12 15:44 UTC, lindgrenj6 requested changes

2020-10-13 06:21 UTC, slemrmartin commented on spec/topological_inventory/sync/metrics_spec.rb
> +RSpec.describe TopologicalInventory::Sync::Metrics do
@lindgrenj6 this is different than openshift's test. It's testing only this class and never reaches any functionality of prometheus exporter gem

2020-10-13 18:52 UTC, syncrou commented on spec/topological_inventory/sync/metrics_spec.rb
> +RSpec.describe TopologicalInventory::Sync::Metrics do
@lindgrenj6 do you have any follow up to https://github.com/RedHatInsights/topological_inventory-sync/pull/72#discussion_r503692912

2020-10-13 19:45 UTC, lindgrenj6 approved these changes

2020-10-13 19:45 UTC, lindgrenj6 commented on spec/topological_inventory/sync/metrics_spec.rb
> +RSpec.describe TopologicalInventory::Sync::Metrics do
Nope, it looks good. I didn't read close enough to notice it's mocking it.

2020-10-13 19:47 UTC, syncrou approved these changes
Only comment here. I'd like to add a ( or the ) Jira ticket here and add the PR to Jira.

LGTM 👍

2020-10-13 19:47 UTC, merged